# Generated by Django 2.2.14 on 2020-08-05 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_data', '0002_weatherresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherdata',
            options={'verbose_name': '天气数据', 'verbose_name_plural': '天气数据'},
        ),
        migrations.AlterModelOptions(
            name='weatherresult',
            options={'ordering': ['-created'], 'verbose_name': '天气推荐指数', 'verbose_name_plural': '天气推荐指数'},
        ),
    ]
