# Generated by Django 2.2.14 on 2020-07-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hero',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hero',
            name='gender',
            field=models.BooleanField(default=True),
        ),
    ]
