# Generated by Django 2.2.14 on 2020-07-27 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': '区域信息', 'verbose_name_plural': '区域信息'},
        ),
        migrations.AddField(
            model_name='region',
            name='is_display',
            field=models.BooleanField(default=False, verbose_name='是否在地图上显示'),
        ),
        migrations.AddField(
            model_name='region',
            name='is_municipality',
            field=models.BooleanField(default=False, null=True, verbose_name='是否为直辖市'),
        ),
        migrations.AddField(
            model_name='region',
            name='is_province_capital',
            field=models.BooleanField(default=False, null=True, verbose_name='是否为省会'),
        ),
        migrations.AddField(
            model_name='region',
            name='is_province_municipality',
            field=models.BooleanField(default=False, null=True, verbose_name='是否为省直辖'),
        ),
        migrations.AddField(
            model_name='region',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='region',
            name='level',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='区域级别'),
        ),
        migrations.AddField(
            model_name='region',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='区域编号'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=30, verbose_name='区域名称'),
        ),
        migrations.AlterField(
            model_name='region',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='region.Region', verbose_name='父级区域'),
        ),
    ]
