# Generated by Django 2.2.14 on 2020-07-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0003_auto_20200727_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='is_display',
            field=models.BooleanField(default=False, verbose_name='是否在地图上显示'),
        ),
        migrations.AddField(
            model_name='region',
            name='is_municipality',
            field=models.BooleanField(default=False, null=True, verbose_name='是否为直辖市'),
        ),
        migrations.AddField(
            model_name='region',
            name='is_province_capital',
            field=models.BooleanField(default=False, null=True, verbose_name='是否为省会'),
        ),
        migrations.AddField(
            model_name='region',
            name='is_province_municipality',
            field=models.BooleanField(default=False, null=True, verbose_name='是否为省直辖'),
        ),
        migrations.AddField(
            model_name='region',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='region',
            name='level',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='区域级别'),
        ),
        migrations.AddField(
            model_name='region',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='经度'),
        ),
    ]
