# Generated by Django 2.2.14 on 2020-08-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0004_auto_20200727_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='short_name',
            field=models.CharField(default=models.CharField(max_length=30, verbose_name='区域名称'), max_length=20, verbose_name='区域名称(短)'),
        ),
    ]
