print('Python公开课调查问卷')
# input info
sex = input('请输入您的性别: ')
age = input('请输入您的年龄: ')
city = input('请输入您所在的城市: ')
level = input('请输入您目前的Python学习情况: ')
os = input('请输入您使用什么操作系统来学习Python: ')
target = input('请输入您学习Python的目的: ')
use = input('请输入您最想使用Python解决的难题: ')
suggest = input('您对本课程有哪些期待和想法: ')
# print info
print('\n调查结果')
print(f'您的性别为: {sex}')
print(f'您的年龄为: {age}')
print(f'您所在的城市为: {city}')
print(f'您目前的Python学习情况是: {level}')
print(f'您使用的操作系统是: {os}')
print(f'您学习Python的目的是: {target}')
print(f'您最想使用Python解决的难题是: {use}')
print(f'您对本课程期待和想法是: {suggest}')
